services:
  - type: web
    name: gymflow-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn gym_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: gymflow-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: gymflow-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: gymflow-db
    plan: starter
    databaseName: gymflow
    user: gymflow_user

